export const LOCAL_STORAGE_WRITE_ERROR = 'LOCAL_STORAGE_WRITE_ERROR';
export const LOCAL_STORAGE_READ_ERROR = 'LOCAL_STORAGE_READ_ERROR';
export const LOCAL_STORAGE_CLEAN_ERROR = 'LOCAL_STORAGE_CLEAN_ERROR';
